# -*- coding: utf-8 -*-
"""assignment-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1kSoBObubvb7QxXKBP8RlcnFaYVsIaV
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/healthcare-dataset.csv')
df.head()

df.drop(['id'],axis=1,inplace=True)
df.fillna(value=df["bmi"].mean(),inplace=True)

sns.pairplot(df)
plt.show()