import numpy as np

zeros=np.zeros(10)
print(zeros)
ones=np.ones(10)
print(ones)
fives=np.full(10,5)
print(fives)
arr=np.arange(10,51)
print(arr)
arr2=np.arange(10,51,2)
print(arr2)
arr3=np.arange(0,9).reshape(3,3)
print(arr3)
arr4=np.eye(3,3)
print(arr4)
ran_num=np.random.rand()
print(ran_num)
ran_nums=np.random.rand(25)
print(ran_nums)
mat=np.arange(1,26).reshape(5,5)
print(mat)
print(mat.sum())
print(mat.std())
